"""Lightweight markup -> Markdown converters (RST, Org, MediaWiki,
AsciiDoc, Textile, Creole, LaTeX) and the Pandoc bridge.

This package was carved out of the former single ``star/markup.py`` module.
Its public surface is preserved verbatim: every name that used to be
importable from ``star.markup`` still is, so ``from star.markup import X``
keeps working unchanged.  The sub-modules group the converters by source
format; the precompiled per-line regexes live in ``_regexes``.
"""
from .._runtime import *  # noqa: F401,F403

# Precompiled per-line regexes (formerly module-scope in markup.py).  They
# remain importable from ``star.markup`` for byte-for-byte surface parity.
from ._regexes import (  # noqa: F401
    _AD_ADMONITION_RE,
    _AD_ATTR_RE,
    _AD_BLOCK_ATTR_RE,
    _AD_BLOCK_DELIM_RE,
    _AD_BOLD1_RE,
    _AD_BOLD2_RE,
    _AD_BOLDITALIC_RE,
    _AD_HEADING_RE,
    _AD_ITALIC_RE,
    _AD_LINK_RE,
    _AD_LIST_RE,
    _AD_MONO_RE,
    _AD_NUM_RE,
    _AD_SOURCE_RE,
    _AD_URL_RE,
    _AD_XREF_RE,
    _AD_XREF_TEXT_RE,
    _CR_HEADING_RE,
    _CR_HR_RE,
    _CR_IMG_ALT_RE,
    _CR_IMG_RE,
    _CR_ITALIC_RE,
    _CR_LINK_PIPE_RE,
    _CR_LINK_RE,
    _CR_NOWIKI_RE,
    _CR_NUM_RE,
    _CR_TABLE_HDR_RE,
    _MW_BOLD_RE,
    _MW_CELL_SEP_RE,
    _MW_EXTLINK_BARE_RE,
    _MW_EXTLINK_TEXT_RE,
    _MW_FILE_RE,
    _MW_HEADER_CELL_RE,
    _MW_HEADING_RE,
    _MW_ITALIC_RE,
    _MW_ROW_SEP_RE,
    _MW_TEMPLATE_RE,
    _MW_WIKILINK_PIPE_RE,
    _MW_WIKILINK_RE,
    _ORG_BLOCK_BEGIN_RE,
    _ORG_BLOCK_END_RE,
    _ORG_BOLD_RE,
    _ORG_CODE_RE,
    _ORG_COMMENT_RE,
    _ORG_DIRECTIVE_RE,
    _ORG_DRAWER_RE,
    _ORG_FOOTNOTE_RE,
    _ORG_HEADLINE_RE,
    _ORG_ITALIC_RE,
    _ORG_LINK_BARE_RE,
    _ORG_LINK_DESC_RE,
    _ORG_LIST_RE,
    _ORG_OLIST_RE,
    _ORG_PRIORITY_RE,
    _ORG_STATS_RE,
    _ORG_STRIKE_RE,
    _ORG_TABLE_SEP_RE,
    _ORG_TAGS_RE,
    _ORG_TODO_RE,
    _ORG_VERBATIM_RE,
    _RST_BOLD_RE,
    _RST_CODE_RE,
    _RST_DIRECTIVE_RE,
    _RST_HYPERLINK_RE,
    _RST_ITALIC_RE,
    _RST_NAMEDREF_RE,
    _TX_BOLD1_RE,
    _TX_BOLD2_RE,
    _TX_BULLET_RE,
    _TX_CODE_RE,
    _TX_HEADING_RE,
    _TX_ITALIC1_RE,
    _TX_ITALIC2_RE,
    _TX_LINK_RE,
    _TX_NUM_RE,
)

# The public converters (each a pure ``str -> str`` except the Pandoc bridge).
from .asciidoc import _asciidoc_to_md  # noqa: F401
from .creole import _creole_to_md  # noqa: F401
from .latex import _latex_to_md  # noqa: F401
from .mediawiki import _mediawiki_to_md  # noqa: F401
from .orgmode import _orgmode_to_md  # noqa: F401
from .pandoc import _pandoc_convert  # noqa: F401
from .rst import _rst_to_md  # noqa: F401
from .textile import _textile_to_md  # noqa: F401

# Names this package owns and re-exports (converters + regexes).  Names pulled
# in via ``from .._runtime import *`` keep whatever export status they had there.
__all__ = [
    # Converters
    "_asciidoc_to_md",
    "_creole_to_md",
    "_latex_to_md",
    "_mediawiki_to_md",
    "_orgmode_to_md",
    "_pandoc_convert",
    "_rst_to_md",
    "_textile_to_md",
    # AsciiDoc regexes
    "_AD_ADMONITION_RE",
    "_AD_ATTR_RE",
    "_AD_BLOCK_ATTR_RE",
    "_AD_BLOCK_DELIM_RE",
    "_AD_BOLD1_RE",
    "_AD_BOLD2_RE",
    "_AD_BOLDITALIC_RE",
    "_AD_HEADING_RE",
    "_AD_ITALIC_RE",
    "_AD_LINK_RE",
    "_AD_LIST_RE",
    "_AD_MONO_RE",
    "_AD_NUM_RE",
    "_AD_SOURCE_RE",
    "_AD_URL_RE",
    "_AD_XREF_RE",
    "_AD_XREF_TEXT_RE",
    # Creole regexes
    "_CR_HEADING_RE",
    "_CR_HR_RE",
    "_CR_IMG_ALT_RE",
    "_CR_IMG_RE",
    "_CR_ITALIC_RE",
    "_CR_LINK_PIPE_RE",
    "_CR_LINK_RE",
    "_CR_NOWIKI_RE",
    "_CR_NUM_RE",
    "_CR_TABLE_HDR_RE",
    # MediaWiki regexes
    "_MW_BOLD_RE",
    "_MW_CELL_SEP_RE",
    "_MW_EXTLINK_BARE_RE",
    "_MW_EXTLINK_TEXT_RE",
    "_MW_FILE_RE",
    "_MW_HEADER_CELL_RE",
    "_MW_HEADING_RE",
    "_MW_ITALIC_RE",
    "_MW_ROW_SEP_RE",
    "_MW_TEMPLATE_RE",
    "_MW_WIKILINK_PIPE_RE",
    "_MW_WIKILINK_RE",
    # Org-mode regexes
    "_ORG_BLOCK_BEGIN_RE",
    "_ORG_BLOCK_END_RE",
    "_ORG_BOLD_RE",
    "_ORG_CODE_RE",
    "_ORG_COMMENT_RE",
    "_ORG_DIRECTIVE_RE",
    "_ORG_DRAWER_RE",
    "_ORG_FOOTNOTE_RE",
    "_ORG_HEADLINE_RE",
    "_ORG_ITALIC_RE",
    "_ORG_LINK_BARE_RE",
    "_ORG_LINK_DESC_RE",
    "_ORG_LIST_RE",
    "_ORG_OLIST_RE",
    "_ORG_PRIORITY_RE",
    "_ORG_STATS_RE",
    "_ORG_STRIKE_RE",
    "_ORG_TABLE_SEP_RE",
    "_ORG_TAGS_RE",
    "_ORG_TODO_RE",
    "_ORG_VERBATIM_RE",
    # reStructuredText regexes
    "_RST_BOLD_RE",
    "_RST_CODE_RE",
    "_RST_DIRECTIVE_RE",
    "_RST_HYPERLINK_RE",
    "_RST_ITALIC_RE",
    "_RST_NAMEDREF_RE",
    # Textile regexes
    "_TX_BOLD1_RE",
    "_TX_BOLD2_RE",
    "_TX_BULLET_RE",
    "_TX_CODE_RE",
    "_TX_HEADING_RE",
    "_TX_ITALIC1_RE",
    "_TX_ITALIC2_RE",
    "_TX_LINK_RE",
    "_TX_NUM_RE",
]
